In [2]:
import numpy as np

a = np.arange(50)
print(a)
print(f"Média: {np.mean(a)}")
print(f"Raiz: {np.sqrt(a)}")
print(f"Max: {np.max(a)}")
print(f"Min: {np.min(a)}")


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
Média: 24.5
Raiz: [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739 3.87298335 4.         4.12310563
 4.24264069 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152
 4.89897949 5.         5.09901951 5.19615242 5.29150262 5.38516481
 5.47722558 5.56776436 5.65685425 5.74456265 5.83095189 5.91607978
 6.         6.08276253 6.164414   6.244998   6.32455532 6.40312424
 6.4807407  6.55743852 6.63324958 6.70820393 6.78232998 6.8556546
 6.92820323 7.        ]
Max: 49
Min: 0


In [6]:
print(a)

b = a.reshape(5,10)
print(b)
print(np.sum(b))
print(np.sum(b, axis=0))
print(np.sum(b, axis=1))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
1225
[100 105 110 115 120 125 130 135 140 145]
[ 45 145 245 345 445]


In [8]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [5, 6, 7, 8]])

print(arr.shape)

(3, 4)


In [9]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [10]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [11]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)
    

1
2
3
4
5
6


In [16]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

ab = arr.reshape(3,2)
print(ab)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [21]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr3 = np.array([[15, 16], [17, 18]])

arr = np.concatenate((arr1, arr2, arr3), axis=1)
print(arr)

ar = np.concatenate((arr1, arr2, arr3))
print(ar)

[[ 1  2  5  6 15 16]
 [ 3  4  7  8 17 18]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [15 16]
 [17 18]]


In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 14, 15, 16, 17 ])

newarr = np.array_split(arr, 3)

print(newarr)
print(type(newarr))
list1 = newarr[0]
print(list1)
print(newarr[1][1])

[array([1, 2, 3, 4]), array([ 5,  6, 14]), array([15, 16, 17])]
<class 'list'>
[1 2 3 4]
6
