In [3]:
print('Hola mundo')

Hola mundo


**Explicação:**ola pessoal

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr[0],arr[2])

print(np.__version__)
print(type(arr))

[1 2 3 4 5]
1 3
2.3.4
<class 'numpy.ndarray'>


In [14]:
import numpy as np

arr = np.array([
    [1,2,3,4,5], 
    [6,7,8,9,10]
])

print(arr[0, 1])
print(arr[1,3])

2
9


In [17]:
import numpy as np

arr = np.array([ [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[7, 8, 9], [10, 11, 15]] ])

print(arr[2, 1, 2])

15


In [25]:
import numpy as np

arr = np.array([11, 12, 13, 14, 15, 16, 17])
print(arr[1:5])
print(arr[0:5:2])
print(arr[:6])

[12 13 14 15]
[11 13 15]
[11 12 13 14 15 16]
